# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  ruby: circleci/ruby@1.1.2

jobs:
  lint:
    docker:
      - image: "golangci/golangci-lint:v1.32.2"

    steps:
      - checkout
      - run: golangci-lint run -v

  build:
    docker:
      # specify the version
      - image: "circleci/golang:1.15"

    working_directory: /go/src/github.com/mmmorris1975/aws-runas

    environment:
      GO111MODULE: "on"

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -ldflags '-X main.Version=0.0.1-0-circle' -o build/aws-runas

      - persist_to_workspace:
          root: build
          paths: aws-runas

  test:
    docker:
      - image: "circleci/ruby:2.7-buster"

    steps:
      - checkout

      - attach_workspace:
          at: build

      # This is only really useful for configuring IAM credentials.  The advanced config file setup
      # required to test aws-runas can't be easily handled with the orb.
      - aws-cli/setup:
          skip-install-check: false
          aws-region: AWS_DEFAULTREGION
          aws-access-key-id: AWS_ACCESSKEY
          aws-secret-access-key: AWS_SECRETKEY

#      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
#      - run: mkdir -p /var/tmp/rspec
      - ruby/install-deps
      - ruby/rspec-test:
          out-path: /var/tmp/rspec
#      - run:
#          command: bundle exec rspec
#          when: always
#          environment:

#      - store_test_results:
#          path: /var/tmp/rspec

workflows:
  version: 2

  # So far we don't have a 'requires' in build for lint, maybe something to change? I mean, who doesn't like clean code?
  build_and_test:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build